# Generated by Django 3.0.6 on 2020-06-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bboxes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keysession', models.TextField(max_length=200)),
                ('classname', models.TextField(max_length=100)),
                ('xmin', models.IntegerField()),
                ('xmax', models.IntegerField()),
                ('ymin', models.IntegerField()),
                ('ymax', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keysession', models.TextField(max_length=200)),
                ('filename', models.TextField(max_length=100)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('depth', models.IntegerField()),
                ('segmented', models.IntegerField()),
            ],
        ),
    ]
